name: IPTV 自动更新
on:
  schedule:
    - cron: '0 17 */3 * *'  # 每3天 北京时间 01:00
  workflow_dispatch:        # 手动触发

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 60     # 1小时强制结束
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip install requests

      - name: 确保 output 文件夹存在
        run: mkdir -p output

      - name: 运行主程序
        run: python main.py

      - name: 查看生成结果
        run: ls -la output/

      - name: 提交更新到仓库
        uses: EndBug/add-and-commit@v9
        with:
          message: "自动更新直播源 $(date +'%Y-%m-%d %H:%M')"
          add: "output/lives.txt output/unused.txt config/input.txt"
          default_author: github_actions
